from typing_extensions import TypedDict


class MacVod(TypedDict, total=False):
    vod_id: int
    type_id: int
    type_id_1: int
    group_id: int
    vod_name: str
    vod_sub: str
    vod_en: str
    vod_status: int
    vod_letter: str
    vod_color: str
    vod_tag: str
    vod_class: str
    vod_pic: str
    vod_pic_thumb: str
    vod_pic_slide: str
    vod_actor: str
    vod_director: str
    vod_writer: str
    vod_behind: str
    vod_blurb: str
    vod_remarks: str
    vod_pubdate: str
    vod_total: int
    vod_serial: str
    vod_tv: str
    vod_weekday: str
    vod_area: str
    vod_lang: str
    vod_year: str
    vod_version: str
    vod_state: str
    vod_author: str
    vod_jumpurl: str
    vod_tpl: str
    vod_tpl_play: str
    vod_tpl_down: str
    vod_isend: int
    vod_lock: int
    vod_level: int
    vod_copyright: int
    vod_points: int
    vod_points_play: int
    vod_points_down: int
    vod_hits: int
    vod_hits_day: int
    vod_hits_week: int
    vod_hits_month: int
    vod_duration: str
    vod_up: int
    vod_down: int
    vod_score: float

    vod_score_all: int
    vod_score_num: int
    vod_time: int
    vod_time_add: int
    vod_time_hits: int
    vod_time_make: int
    vod_trysee: int
    vod_douban_id: int
    vod_douban_score: float
    vod_reurl: str
    vod_rel_vod: str
    vod_rel_art: str
    vod_pwd: str
    vod_pwd_url: str
    vod_pwd_play: str
    vod_pwd_play_url: str
    vod_pwd_down: str
    vod_pwd_down_url: str
    vod_content: str
    vod_play_from: str
    vod_play_server: str
    vod_play_note: str
    vod_play_url: str
    vod_down_from: str
    vod_down_server: str
    vod_down_note: str
    vod_down_url: str
    vod_plot: int
    vod_plot_name: str
    vod_plot_detail: str
