class User:
    user_id: int
    group_id: int
    user_name: str
    user_pwd: str
    user_nick_name: str
    user_qq: str
    user_email: str
    user_phone: str
    user_status: int
    user_portrait: str
    user_portrait_thumb: str
    user_openid_qq: str
    user_openid_weixin: str
    user_question: str
    user_answer: str
    user_points: int
    user_points_froze: int
    user_reg_time: int
    user_reg_ip: int
    user_login_time: int
    user_login_ip: int
    user_last_login_time: int
    user_last_login_ip: int
    user_login_num: int
    user_extend: int
    user_random: str
    user_end_time: int
    user_pid: int
    user_pid_2: int
    user_pid_3: int
