# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class MacType(models.Model):
    type_id = models.SmallAutoField(primary_key=True)
    type_name = models.CharField(max_length=60)
    type_en = models.CharField(max_length=60)
    type_sort = models.PositiveSmallIntegerField()
    type_mid = models.PositiveSmallIntegerField()
    type_pid = models.PositiveSmallIntegerField()
    type_status = models.PositiveIntegerField()
    type_tpl = models.CharField(max_length=30)
    type_tpl_list = models.CharField(max_length=30)
    type_tpl_detail = models.CharField(max_length=30)
    type_tpl_play = models.CharField(max_length=30)
    type_tpl_down = models.CharField(max_length=30)
    type_key = models.CharField(max_length=255)
    type_des = models.CharField(max_length=255)
    type_title = models.CharField(max_length=255)
    type_union = models.CharField(max_length=255)
    type_extend = models.TextField(blank=True, null=True)
    type_logo = models.CharField(max_length=255)
    type_pic = models.CharField(max_length=255)
    type_jumpurl = models.CharField(max_length=150)

    class Meta:
        managed = False
        db_table = 'mac_type'


class MacVod(models.Model):
    vod_id = models.AutoField(primary_key=True)
    type_id = models.SmallIntegerField()
    type_id_1 = models.PositiveSmallIntegerField()
    group_id = models.PositiveSmallIntegerField()
    vod_name = models.CharField(max_length=255)
    vod_sub = models.CharField(max_length=255)
    vod_en = models.CharField(max_length=255)
    vod_status = models.PositiveIntegerField()
    vod_letter = models.CharField(max_length=1)
    vod_color = models.CharField(max_length=6)
    vod_tag = models.CharField(max_length=100)
    vod_class = models.CharField(max_length=255)
    vod_pic = models.CharField(max_length=255)
    vod_pic_thumb = models.CharField(max_length=255)
    vod_pic_slide = models.CharField(max_length=255)
    vod_actor = models.CharField(max_length=255)
    vod_director = models.CharField(max_length=255)
    vod_writer = models.CharField(max_length=100)
    vod_behind = models.CharField(max_length=100)
    vod_blurb = models.CharField(max_length=255)
    vod_remarks = models.CharField(max_length=100)
    vod_pubdate = models.CharField(max_length=100)
    vod_total = models.PositiveIntegerField()
    vod_serial = models.CharField(max_length=20)
    vod_tv = models.CharField(max_length=30)
    vod_weekday = models.CharField(max_length=30)
    vod_area = models.CharField(max_length=20)
    vod_lang = models.CharField(max_length=10)
    vod_year = models.CharField(max_length=10)
    vod_version = models.CharField(max_length=30)
    vod_state = models.CharField(max_length=30)
    vod_author = models.CharField(max_length=60)
    vod_jumpurl = models.CharField(max_length=150)
    vod_tpl = models.CharField(max_length=30)
    vod_tpl_play = models.CharField(max_length=30)
    vod_tpl_down = models.CharField(max_length=30)
    vod_isend = models.PositiveIntegerField()
    vod_lock = models.PositiveIntegerField()
    vod_level = models.PositiveIntegerField()
    vod_copyright = models.PositiveIntegerField()
    vod_points = models.PositiveSmallIntegerField()
    vod_points_play = models.PositiveSmallIntegerField()
    vod_points_down = models.PositiveSmallIntegerField()
    vod_hits = models.PositiveIntegerField()
    vod_hits_day = models.PositiveIntegerField()
    vod_hits_week = models.PositiveIntegerField()
    vod_hits_month = models.PositiveIntegerField()
    vod_duration = models.CharField(max_length=10)
    vod_up = models.PositiveIntegerField()
    vod_down = models.PositiveIntegerField()
    vod_score = models.DecimalField(max_digits=3, decimal_places=1)
    vod_score_all = models.PositiveIntegerField()
    vod_score_num = models.PositiveIntegerField()
    vod_time = models.PositiveIntegerField()
    vod_time_add = models.PositiveIntegerField()
    vod_time_hits = models.PositiveIntegerField()
    vod_time_make = models.PositiveIntegerField()
    vod_trysee = models.PositiveSmallIntegerField()
    vod_douban_id = models.PositiveIntegerField()
    vod_douban_score = models.DecimalField(max_digits=3, decimal_places=1)
    vod_reurl = models.CharField(max_length=255)
    vod_rel_vod = models.CharField(max_length=255)
    vod_rel_art = models.CharField(max_length=255)
    vod_pwd = models.CharField(max_length=10)
    vod_pwd_url = models.CharField(max_length=255)
    vod_pwd_play = models.CharField(max_length=10)
    vod_pwd_play_url = models.CharField(max_length=255)
    vod_pwd_down = models.CharField(max_length=10)
    vod_pwd_down_url = models.CharField(max_length=255)
    vod_content = models.TextField()
    vod_play_from = models.CharField(max_length=255)
    vod_play_server = models.CharField(max_length=255)
    vod_play_note = models.CharField(max_length=255)
    vod_play_url = models.TextField()
    vod_down_from = models.CharField(max_length=255)
    vod_down_server = models.CharField(max_length=255)
    vod_down_note = models.CharField(max_length=255)
    vod_down_url = models.TextField()
    vod_plot = models.PositiveIntegerField()
    vod_plot_name = models.TextField()
    vod_plot_detail = models.TextField()

    class Meta:
        managed = False
        db_table = 'mac_vod'
